### DISCUSSION TITLE
OAuth2 Azure: login attempt fails with property [io.featurehub.db.model.DbFeatureValue.feature] expected to be an embedded or *ToOne bean for query - excluding it.

### DISCUSSION THREAD

**Discussion by hostalp** [featurehub-io/featurehub#813] [Q&A] [answered]
Hello,
I'm trying to get the OAuth2 authentication with Azure to work.

I configured it as shown below and the Azure setup has been done accordingly.
Now the authentication attempt appears to succeed, I'm returned back to the featurehub, but I end up at the login page again and there's the following in the log (I replaced some potentially sensitive data):
```
{"@timestamp":"2022-07-26T17:39:30.181+0000","message":"{\"ts\":1658857170179,\"change\":\"I\",\"type\":\"DbPerson\",\"id\":\"xyz\",\"data\":{\"passwordAlgorithm\":\"PBKDF2WithHmacSHA512\",\"name\":\"User Name\",\"email\":\"user.name@domain.net\",\"passwordRequiresReset\":false,\"token\":\"xyz\",\"tokenExpiry\":\"2022-08-02T17:39:30.171006\",\"personType\":\"PERSON\",\"whenUpdated\":\"2022-07-26T17:39:30.173\",\"whenCreated\":\"2022-07-26T17:39:30.173\",\"version\":1}}","priority":"INFO","path":"io.ebean.ChangeLog","thread":"ebean-db1","host":"xyz"}
{"@timestamp":"2022-07-26T17:39:30.191+0000","message":"{\"ts\":1658857170190,\"change\":\"U\",\"type\":\"DbPerson\",\"id\":\"xyz\",\"data\":{\"whenUpdated\":\"2022-07-26T17:39:30.187\",\"version\":2,\"whenLastAuthenticated\":\"2022-07-26T17:39:30.187455Z\",\"token\":null,\"tokenExpiry\":null},\"oldData\":{\"whenUpdated\":\"2022-07-26T17:39:30.173\",\"version\":1,\"whenLastAuthenticated\":null,\"token\":\"xyz\",\"tokenExpiry\":\"2022-08-02T17:39:30.171006\"}}","priority":"INFO","path":"io.ebean.ChangeLog","thread":"ebean-db2","host":"xyz"}
{"@timestamp":"2022-07-26T17:39:30.199+0000","message":"groups for person class Person {
    id: class PersonId {
        id: xyz
    }
    name: User Name
    email: user.name@domain.net
    personType: person
    other: null
    source: null
    version: 2
    passwordRequiresReset: false
    groups: []
    whenArchived: null
    whenLastAuthenticated: null
    whenLastSeen: null
    additional: []
} are []","priority":"INFO","path":"io.featurehub.db.services.ConvertUtils","thread":"grizzly-http-server-0","host":"xyz"}
{"@timestamp":"2022-07-26T17:39:30.205+0000","message":"{\"ts\":1658857170205,\"change\":\"I\",\"type\":\"DbLogin\",\"id\":\"xyz\",\"data\":{\"lastSeen\":\"2022-07-26T17:39:30.199987Z\",\"person\":{\"id\":\"xyz\"}}}","priority":"INFO","path":"io.ebean.ChangeLog","thread":"ebean-db2","host":"xyz"}
{"@timestamp":"2022-07-26T17:39:32.479+0000","message":"publishing 5 service accounts to cache default","priority":"INFO","path":"io.featurehub.db.publish.DbCacheSource","thread":"pool-3-thread-1","host":"xyz"}
{"@timestamp":"2022-07-26T17:39:32.494+0000","message":"publishing 21 environments to cache default","priority":"INFO","path":"io.featurehub.db.publish.DbCacheSource","thread":"pool-3-thread-2","host":"xyz"}
{"@timestamp":"2022-07-26T17:39:32.674+0000","message":"property [io.featurehub.db.model.DbFeatureValue.feature] expected to be an embedded or *ToOne bean for query - excluding it.","priority":"ERROR","path":"io.ebean.internal","thread":"pool-3-thread-3","host":"xyz"}
```
So it appears to fail with `property [io.featurehub.db.model.DbFeatureValue.feature] expected to be an embedded or *ToOne bean for query - excluding it.`
Does anyone know what causes this and how to resolve it?

config
```yaml
      # OAuth2 - https://docs.featurehub.io/featurehub/latest/identity.html#_oauth2
      oauth2.redirectUrl: https://featurehub.domain.net/oauth/auth
      oauth2.adminUiUrlSuccess: https://featurehub.domain.net/
      oauth2.adminUiUrlFailure: https://featurehub.domain.net/oauth2-failure
      oauth2.providers: oauth2-azure,oauth2-generic

      oauth2.providers.azure.tenant: xyz
      oauth2.providers.azure.id: xyz
      oauth2.providers.azure.secret: xyz

      oauth2.providers.generic.auth-url: https://riapp.dev.domain.net/authorize
      oauth2.providers.generic.token-url: https://riapp.dev.domain.net/token
      oauth2.providers.generic.id: FeatureHub
      oauth2.providers.generic.secret: xyz
      oauth2.providers.generic.scope: openid
      oauth2.providers.generic.icon.url: https://riapp.dev.domain.net/authorize/login/favicon.ico
      oauth2.providers.generic.icon.background-color: 0xFFF44336
      oauth2.providers.generic.icon.text: Sign in via RIAPP-DEV
```
Featurehub 1.5.8
