### ISSUE TITLE
Error on configure IDP with provider oauth2-keycloak

### ISSUE THREAD

**Issue by theanaoliveira** [featurehub-io/featurehub#1135]
**Describe the bug**

After configure oauth2 as a oauth2-keycloak, the redirect url put "/auth" on my keycloak URL and I got the error: page not found

My issuer url is: http://keycloak.localhost/keycloak/realms/CIAF

 Which area does this issue belong to?

* [x] FeatureHub Admin Web app
* [ ] SDK
* [ ] SDK examples
* [ ] Documentation
* [ ] Other

**To Reproduce**

1. Configure oauth2 using environmentVars:

```
auth.disable-login: "false"
auth.userMustBeCreatedFirst: "false"

oauth2.providers: oauth2-keycloak
oauth2.redirectUrl: http://featurehub.localhost/oauth/auth
oauth2.adminUiUrlSuccess: http://featurehub.localhost/
oauth2.adminUiUrlFailure: http://featurehub.localhost/oauth2-failure

oauth2.providers.keycloak.secret: {{CLIENT_SECRET}}
oauth2.providers.keycloak.url: http://keycloak.localhost/keycloak
oauth2.providers.keycloak.realm: CIAF
oauth2.providers.keycloak.id: {{CLIENT_ID}}
``` 

3. Click on Sign in with Keycloak

**Expected behavior**

Not put "/auth"

**Screenshots**

![Screenshot_2](https://github.com/featurehub-io/featurehub/assets/15036668/169782f6-0b97-43f2-a4be-de7969c30532)

**Versions**
 - featurehub/party-server:1.7.2-RC and featurehub/mr:1.5.8

**Comment by rvowles** [comment]
Sorry for the late reply, did you resolve this? If you could try and use the generic oauth config setting and see if that works? Keycloak confnig may have moved on since we did that integration, which version of Keycloak are you using?

**Comment by theanaoliveira** [comment]
Thanks for the answer, I'm using keycloak version 23.0.4, with this docker image: quay.io/keycloak/keycloak:23.0.4, and yes they removed /auth by default.

I tried using the generic configuration, but the redirect to the URL "/oauth/auth" didn't work

```
auth.disable-login: "false"
auth.userMustBeCreatedFirst: "false"

oauth2.adminUiUrlFailure: http://featurehub.localhost/oauth2-failure
oauth2.adminUiUrlSuccess: http://featurehub.localhost/
oauth2.providers: oauth2-generic
oauth2.providers.generic.auth-url: http://keycloak.localhost/keycloak/realms/CIAF/protocol/openid-connect/auth
oauth2.providers.generic.icon.background-color: "0xDDDDDDD"
oauth2.providers.generic.icon.text: Oauth2
oauth2.providers.generic.icon.url: any_image.png
oauth2.providers.generic.id: {{CLIENT_ID}}
oauth2.providers.generic.scope: profile email openid
oauth2.providers.generic.secret: {{CLIENT_SECRET}}
oauth2.providers.generic.token-url: http://keycloak.localhost/keycloak/realms/CIAF/protocol/openid-connect/token
oauth2.redirectUrl: http://featurehub.localhost/oauth/auth
```

It's correct?

**Comment by rvowles** [comment]
```oauth2.redirectUrl: http://featurehub.localhost/oauth/auth```

that is the correct url if your base url is http://featurehub.localhost - are you able to look at the  logs and see what happens? There might be a clue as to what is happening there?

Your auth-url should direct you to the correct location in Keycloak, so I presume you are able to login into Keycloak and your error is now occurring when it comes back into FeatureHub?

**Comment by theanaoliveira** [comment]
Yes, I can log in, after entering my username and password I receive the page below:

![image](https://github.com/featurehub-io/featurehub/assets/15036668/9aabc115-c0c2-47fd-b567-7d5b06bcf81e)

I changed my values.yaml file and try again with a path /hub

```
global:
  urlPath: /hub

postgresql:
  enabled: false

edge:
  enabled: true
  envAsApplicationProperties: false

managementRepository:
  image:
    repository: featurehub/party-server
    tag: 1.7.2-RC
  ingress:
    className: apisix
    enabled: true
    hosts:
      - host: featurehub.localhost
        paths:
          - path: /hub
            pathType: Prefix
    tls: []
  environmentVars:
    db.connections: "20"
    db.password: "postgres"
    db.url: "jdbc:postgresql://postgres-postgresql.featurehub:5432/postgres"
    db.username: "postgres"
    
    auth.disable-login: "false"
    auth.userMustBeCreatedFirst: "false"

    oauth2.adminUiUrlFailure: http://featurehub.localhost/hub/oauth2-failure
    oauth2.adminUiUrlSuccess: http://featurehub.localhost/hub/
    oauth2.providers: oauth2-generic
    oauth2.providers.generic.auth-url: http://keycloak.localhost/keycloak/realms/FEATUREHUB/protocol/openid-connect/auth
    oauth2.providers.generic.icon.background-color: "0xDDDDDDD"
    oauth2.providers.generic.icon.text: Keycloak
    oauth2.providers.generic.icon.url: https://www.xpand-it.com/wp-content/uploads/2020/06/Keycloak-logo.png
    oauth2.providers.generic.id: hub
    oauth2.providers.generic.scope: profile email openid
    oauth2.providers.generic.secret: Lr3FNNl10Ia9MKy1mjYheJXau04clxh1
    oauth2.providers.generic.token-url: http://keycloak.localhost/keycloak/realms/FEATUREHUB/protocol/openid-connect/token
    oauth2.redirectUrl: http://featurehub.localhost/hub/oauth/auth

  envAsApplicationProperties: false
```

keycloak:

![image](https://github.com/featurehub-io/featurehub/assets/15036668/03453fbd-459e-4b6d-ae35-b4ea765d1c29)

Management featurehub:

![image](https://github.com/featurehub-io/featurehub/assets/15036668/ebe2ceb1-0d9b-44b8-b7e0-6c89e462b8f0)

Logs:

```
{"@timestamp":"2024-04-08T13:58:09.241+0000","message":"Exception URI http://featurehub.localhost:80/hub/oauth/auth?state=oauth2-generic%3B23b0764e-bd2d-45ed-9dee-f06c80e63508&session_state=d70951c8-4da6-4682-adc7-915af316c9ee&iss=http%3A%2F%2Fkeycloak.localhost%2Fkeycloak%2Frealms%2FFEATUREHUB&code=7c50b1e2-0714-4959-8d9a-e9e1692671a4.d70951c8-4da6-4682-adc7-915af316c9ee.07969444-b3a0-422b-80a6-c8ed19eea49d","priority":"WARN","path":"io.featurehub.lifecycle.TelemetryApplicationEventListener$TelemetryRequestEventListener","thread":"grizzly-http-server-7","host":"featurehub-management-repository-f44b67665-qv255"}
{"@timestamp":"2024-04-08T13:58:09.242+0000","message":"Failed jersey request","priority":"ERROR","path":"io.featurehub.jersey.config.LocalExceptionMapper","thread":"grizzly-http-server-7","stack_trace":"jakarta.ws.rs.ProcessingException: java.net.UnknownHostException: keycloak.localhost\n\torg.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:270) ~[jersey-client-3.1.1.jar:?]\n\torg.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:300) ~[jersey-client-3.1.1.jar:?]\n\torg.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:662) ~[jersey-client-3.1.1.jar:?]\n\torg.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:697) ~[jersey-client-3.1.1.jar:?]\n\torg.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:691) ~[jersey-client-3.1.1.jar:?]\n\torg.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[jersey-common-3.1.1.jar:?]\n\torg.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[jersey-common-3.1.1.jar:?]\n\torg.glassfish.jersey.internal.Errors.process(Errors.java:205) ~[jersey-common-3.1.1.jar:?]\n\torg.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390) ~[jersey-common-3.1.1.jar:?]\n\torg.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:691) ~[jersey-client-3.1.1.jar:?]\n\torg.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:661) ~[jersey-client-3.1.1.jar:?]\n\torg.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:439) ~[jersey-client-3.1.1.jar:?]\n\torg.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:345) ~[jersey-client-3.1.1.jar:?]\n\tio.featurehub.web.security.oauth.OAuth2JerseyClient.requestAccess(OAuth2JerseyClient.kt:44) ~[security-oauth-1.1-SNAPSHOT.jar:?]\n\tio.featurehub.web.security.oauth.OauthResource.token(OauthResource.kt:60) ~[security-oauth-1.1-SNAPSHOT.jar:?]\n\tjdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]\n\tjdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]\n\tjdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]\n\tjava.lang.reflect.Method.invoke(Unknown Source) ~[?:?]\n\torg.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[jersey-server-3.1.1.jar:?]\n\torg.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:134) ~[jersey-server-3.1.1.jar:?]\n\torg.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:177) ~[jersey-server-3.1.1.jar:?]\n\torg.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176) ~[jersey-server-3.1.1.jar:?]\n\torg.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:81) ~[jersey-server-3.1.1.jar:?]\n\torg.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478) ~[jersey-server-3.1.1.jar:?]\n\torg.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400) ~[jersey-server-3.1.1.jar:?]\n\torg.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81) ~[jersey-server-3.1.1.jar:?]\n\torg.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:261) [jersey-server-3.1.1.jar:?]\n\torg.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [jersey-common-3.1.1.jar:?]\n\torg.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [jersey-common-3.1.1.jar:?]\n\torg.glassfish.jersey.internal.Errors.process(Errors.java:292) [jersey-common-3.1.1.jar:?]\n\torg.glassfish.jersey.internal.Errors.process(Errors.java:274) [jersey-common-3.1.1.jar:?]\n\torg.glassfish.jersey.internal.Errors.process(Errors.java:244) [jersey-common-3.1.1.jar:?]\n\torg.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [jersey-common-3.1.1.jar:?]\n\torg.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:240) [jersey-server-3.1.1.jar:?]\n\torg.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:697) [jersey-server-3.1.1.jar:?]\n\torg.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:367) [jersey-container-grizzly2-http-3.1.1.jar:?]\n\torg.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:190) [grizzly-http-server-4.0.0.jar:4.0.0]\n\torg.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535) [grizzly-framework-4.0.0.jar:4.0.0]\n\torg.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515) [grizzly-framework-4.0.0.jar:4.0.0]\n\tjava.lang.Thread.run(Unknown Source) [?:?]\n\tCaused by: java.net.UnknownHostException: keycloak.localhost\n\tjava.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:?]\n\tjava.net.Socket.connect(Unknown Source) ~[?:?]\n\tsun.net.NetworkClient.doConnect(Unknown Source) ~[?:?]\n\tsun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]\n\tsun.net.www.http.HttpClient.openServer(Unknown Source) ~[?:?]\n\tsun.net.www.http.HttpClient.<init>(Unknown Source) ~[?:?]\n\tsun.net.www.http.HttpClient.New(Unknown Source) ~[?:?]\n\tsun.net.www.http.HttpClient.New(Unknown Source) ~[?:?]\n\tsun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source) ~[?:?]\n\tsun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:?]\n\tsun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:?]\n\tsun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source) ~[?:?]\n\tsun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:?]\n\tsun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:?]\n\tjava.net.HttpURLConnection.getResponseCode(Unknown Source) ~[?:?]\n\torg.glassfish.jersey.client.internal.HttpUrlConnector.handleException(HttpUrlConnector.java:551) ~[jersey-client-3.1.1.jar:?]\n\torg.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:377) ~[jersey-client-3.1.1.jar:?]\n\torg.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:268) ~[jersey-client-3.1.1.jar:?]","host":"featurehub-management-repository-f44b67665-qv255"}
```
