### ISSUE TITLE
Kinesis stream name appears to be hardcoded

### ISSUE THREAD

**Issue by rickybasra** [featurehub-io/featurehub#1150]
**Describe the bug**
Kinesis stream name appears to be hardcoded i.e. featurehub-mr-stream

 Which area does this issue belong to?

* [X] FeatureHub Admin Web app
* [ ] SDK
* [ ] SDK examples
* [ ] Documentation
* [ ] Other

**To Reproduce**
1. Follow guide on configuring aws kinesis 
https://docs.featurehub.io/featurehub/latest/configuration.html#_aws_kinesis
2. Run `helm get values featurehub --all | grep featurehub-mr-stream` and you'll there are no values of `featurehub-mr-stream` yet this is present in  

Used values 
```  
global:
  environmentVars:
      nats.urls: "nats://featurehub-nats"
      nats.enabled: false
      dacha1.enabled: false
      dacha2.enabled: true
      cloudevents.kinesis.enabled: true
      cloudevents.kinesis.aws.region: eu-west-1
      cloudevents.kinesis.endpointUrl: https://kinesis.eu-west-1.amazonaws.com
      cloudevents.mr-edge.kinesis.stream-name: featurehub-mr-edge
      cloudevents.mr-edge.kinesis.randomise-partition-key: false
      cloudevents.stats.kinesis.stream-name: featurehub-stats
      cloudevents.mr-dacha2.kinesis.stream-name: featurehub-mr-dacha2
      cloudevents.mr-dacha2.kinesis.randomise-partition-key: false
      cloudevents.inbound.stream-names: featurehub-edge-updates
      cloudevents.edge-mr.kinesis.stream-name: featurehub-edge-updates
```

 Check pod logs and there are errors 
 ```
{"@timestamp":"2024-04-22T15:43:47.263+0000","message":"Error when trying to send in background to Kinesis, will try later","priority":"ERROR","path":"io.featurehub.events.kinesis.KinesisFactoryImpl","thread":"pool-4-thread-1","stack_trace":"java.util.concurrent.ExecutionException: software.amazon.awssdk.services.kinesis.model.AccessDeniedException: User: arn:aws:sts::12345676:assumed-role/role_EKS-APP-NODE-ROLE-FEATUREHUB/i-0d031axxxxxxx is not authorized to perform: kinesis:PutRecord on resource: arn:aws:kinesis:eu-west-1:12345676:stream/featurehub-mr-stream because no identity-based policy allows the kinesis:PutRecord action (Service: Kinesis, Status Code: 400, Request ID: c4bc3d02-1dff-6f83-9a1c-baf169f0e3fa, Extended Request ID: 
```

**Expected behavior**
Cannot see how or where stream name featurehub-mr-stream is set.

**Screenshots**

**Versions**
 - FeatureHub version [e.g. 1.7.0]
 - Browser [e.g. chrome]

**Additional context**
