### ISSUE TITLE
Error launching mr:1.8.1  from docker image

### ISSUE THREAD

**Issue by jamesphilipps** [featurehub-io/featurehub#1195]
**Describe the bug**
When launching the mr:1.8.1 image, I receive the following error:

```
org.glassfish.hk2.api.MultiException: A MultiException has 3 exceptions.  They are:
1. org.glassfish.hk2.api.UnsatisfiedDependencyException: There was no object available in __HK2_Generated_0 for injection at SystemInjecteeImpl(requiredType=FeatureModelWalker,parent=DbCacheSource,qualifiers={},position=4,optional=false,self=false,unqualified=null,2119255170)
2. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of io.featurehub.db.publish.DbCacheSource errors were found
3. java.lang.IllegalStateException: Unable to perform operation: resolve on io.featurehub.db.publish.DbCacheSource

    org.jvnet.hk2.internal.Collector.throwIfErrors(Collector.java:65) ~[hk2-locator-3.0.6.jar:?]
    org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:249) ~[hk2-locator-3.0.6.jar:?]
    org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:387) ~[hk2-locator-3.0.6.jar:?]
    org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:466) ~[hk2-locator-3.0.6.jar:?]
    org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:59) ~[hk2-locator-3.0.6.jar:?]
    org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:47) ~[hk2-locator-3.0.6.jar:?]
    org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:74) ~[hk2-utils-3.0.6.jar:?]
    java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
    org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:131) ~[hk2-utils-3.0.6.jar:?]
    org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:176) ~[hk2-utils-3.0.6.jar:?]
    org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:98) ~[hk2-locator-3.0.6.jar:?]
    org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2109) ~[hk2-locator-3.0.6.jar:?]
    org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:769) ~[hk2-locator-3.0.6.jar:?]
    org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:732) ~[hk2-locator-3.0.6.jar:?]
    org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:702) ~[hk2-locator-3.0.6.jar:?]
    io.featurehub.Application.lambda$run$0(Application.java:50) ~[mr-1.1-SNAPSHOT.jar:?]
    io.featurehub.health.MetricsHealthRegistration$Companion$configureMetrics$2.configure(MetricsHealthRegistration.kt:55) ~[common-web-1.1-SNAPSHOT.jar:?]
    org.glassfish.jersey.internal.inject.AbstractBinder.invokeConfigure(AbstractBinder.java:256) ~[jersey-common-3.1.7.jar:?]
    org.glassfish.jersey.internal.inject.AbstractBinder.getBindings(AbstractBinder.java:246) ~[jersey-common-3.1.7.jar:?]
    org.glassfish.jersey.internal.inject.Bindings.getBindings(Bindings.java:44) ~[jersey-common-3.1.7.jar:?]
    org.glassfish.jersey.internal.inject.AbstractBinder.lambda$getBindings$1(AbstractBinder.java:248) ~[jersey-common-3.1.7.jar:?]
    java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[?:?]
    java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?]
    java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
    java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
    java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
    java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
    java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
    org.glassfish.jersey.internal.inject.AbstractBinder.getBindings(AbstractBinder.java:249) ~[jersey-common-3.1.7.jar:?]
    org.glassfish.jersey.internal.inject.Bindings.getBindings(Bindings.java:44) ~[jersey-common-3.1.7.jar:?]
    org.glassfish.jersey.inject.hk2.Hk2Helper.bind(Hk2Helper.java:68) ~[jersey-hk2-3.1.7.jar:?]
    org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.register(ImmediateHk2InjectionManager.java:58) ~[jersey-hk2-3.1.7.jar:?]
    org.glassfish.jersey.model.internal.CommonConfig.configureBinders(CommonConfig.java:655) ~[jersey-common-3.1.7.jar:?]
    org.glassfish.jersey.model.internal.CommonConfig.configureMetaProviders(CommonConfig.java:634) ~[jersey-common-3.1.7.jar:?]
    org.glassfish.jersey.server.ResourceConfig.configureMetaProviders(ResourceConfig.java:832) ~[jersey-server-3.1.7.jar:?]
    org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:344) ~[jersey-server-3.1.7.jar:?]
    org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:309) ~[jersey-server-3.1.7.jar:?]
    org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[jersey-common-3.1.7.jar:?]
    org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[jersey-common-3.1.7.jar:?]
    org.glassfish.jersey.internal.Errors.processWithException(Errors.java:232) ~[jersey-common-3.1.7.jar:?]
    org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:308) ~[jersey-server-3.1.7.jar:?]
    org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:273) ~[jersey-server-3.1.7.jar:?]
    org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:260) ~[jersey-server-3.1.7.jar:?]
    org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.<init>(GrizzlyHttpContainer.java:310) ~[jersey-container-grizzly2-http-3.1.7.jar:?]
    org.glassfish.jersey.grizzly2.httpserver.HttpGrizzlyContainer$Companion.makeHandler(HttpGrizzlyContainer.kt:9) ~[common-web-1.1-SNAPSHOT.jar:?]
    io.featurehub.jersey.FeatureHubJerseyHost.start(FeatureHubJerseyHost.kt:99) ~[common-web-1.1-SNAPSHOT.jar:?]
    io.featurehub.health.MetricsHealthRegistration$Companion.startMetricsEndpoint(MetricsHealthRegistration.kt:66) ~[common-web-1.1-SNAPSHOT.jar:?]
    io.featurehub.health.MetricsHealthRegistration$Companion$registerMetrics$2.onStartup(MetricsHealthRegistration.kt:101) ~[common-web-1.1-SNAPSHOT.jar:?]
    org.glassfish.jersey.server.ApplicationHandler.onStartup(ApplicationHandler.java:723) ~[jersey-server-3.1.7.jar:?]
    org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.start(GrizzlyHttpContainer.java:341) ~[jersey-container-grizzly2-http-3.1.7.jar:?]
    org.glassfish.grizzly.http.server.HttpHandlerChain.start(HttpHandlerChain.java:376) ~[grizzly-http-server-4.0.0.jar:4.0.0]
    org.glassfish.grizzly.http.server.HttpHandlerChain.start(HttpHandlerChain.java:376) ~[grizzly-http-server-4.0.0.jar:4.0.0]
    org.glassfish.grizzly.http.server.HttpServer.setupHttpHandler(HttpServer.java:268) ~[grizzly-http-server-4.0.0.jar:4.0.0]
    org.glassfish.grizzly.http.server.HttpServer.start(HttpServer.java:245) ~[grizzly-http-server-4.0.0.jar:4.0.0]
    io.featurehub.jersey.FeatureHubJerseyHost.start(FeatureHubJerseyHost.kt:163) ~[common-web-1.1-SNAPSHOT.jar:?]
    io.featurehub.jersey.FeatureHubJerseyHost.start(FeatureHubJerseyHost.kt:62) ~[common-web-1.1-SNAPSHOT.jar:?]
    io.featurehub.Application.run(Application.java:60) ~[mr-1.1-SNAPSHOT.jar:?]
    io.featurehub.Application.main(Application.java:31) [mr-1.1-SNAPSHOT.jar:?]
    jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
    jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
    jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
    java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
    bathe.BatheBooter.tryMainMethod(BatheBooter.java:149) [bathe-booter-3.2.jar:?]
    bathe.BatheBooter.exec(BatheBooter.java:166) [bathe-booter-3.2.jar:?]
    bathe.BatheBooter.runWithLoader(BatheBooter.java:125) [bathe-booter-3.2.jar:?]
    bathe.BatheBooter.run(BatheBooter.java:115) [bathe-booter-3.2.jar:?]
    bathe.BatheBooter.main(BatheBooter.java:37) [bathe-booter-3.2.jar:?]
    Caused by: org.glassfish.hk2.api.UnsatisfiedDependencyException: There was no object available in __HK2_Generated_0 for injection at SystemInjecteeImpl(requiredType=FeatureModelWalker,parent=DbCacheSource,qualifiers={},position=4,optional=false,self=false,unqualified=null,2119255170)
    org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:52) ~[hk2-locator-3.0.6.jar:?]
    org.jvnet.hk2.internal.ClazzCreator.resolve(ClazzCreator.java:197) ~[hk2-locator-3.0.6.jar:?]
    org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:214) ~[hk2-locator-3.0.6.jar:?]
```

 Which area does this issue belong to?

* [x] FeatureHub Admin Web app
* [ ] SDK
* [ ] SDK examples
* [ ] Documentation
* [ ] Other

**To Reproduce**
Use this compose file (copied from the example repository)

```
version: '3.1'

services:
  postgresql-master:
    image: docker.io/bitnami/postgresql:13
    ports:
      - '5432'
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_DATABASE=postgres
      - ALLOW_EMPTY_PASSWORD=yes
  postgresql-slave:
    image: docker.io/bitnami/postgresql:13
    ports:
      - '5432'
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=yes
  edge-rest-ish:
    # we prefer the slave replica for read requests here
    image: featurehub/edge-rest:1.8.1
    ports:
      - 8553:8553
      - 8701:8701
    depends_on:
      - postgresql-master
      - postgresql-slave
    environment:
      - db.url=jdbc:postgresql://postgresql-master/postgres
      - db.username=postgres
      - db.password=my_password
      - db.minConnections=3
      - db.maxConnections=30
      - db-replica.url=jdbc:postgresql://postgresql-slave/postgres
      - db-replica.username=postgres
      - db-replica.password=my_password
      - db-replica.minConnections=3
      - db-replica.maxConnections=30
      - auth.disable-login=false
      - monitor.port=8701
      - server.port=8553
  admin-app:
    image: featurehub/mr:1.8.1
    ports:
      - 8085:8085
    depends_on:
      - postgresql-master
    environment:
      - db.url=jdbc:postgresql://postgresql-master/postgres
      - db.username=postgres
      - db.password=my_password
      - db.minConnections=3
      - db.maxConnections=30
      - auth.disable-login=false
      - monitor.port=8701
      - server.port=8085

volumes:
  postgresql_master_data:
    driver: local

```

**Expected behavior**
The application launches successfully

**Screenshots**

**Versions**
 - FeatureHub version 1.8.1
